Algoritmo "aula_04_atividade_04"
// Disciplina   : Criação de Aplicações
// Professor   : Frank Portela

// Descrição   : ATIVIDADE PRÁTICA 04
// Escreva um algoritmo em portugol que solicite ao usuário 4 números:
// - Some os números
// - multiplique cada um dos números por 3
// - calcule a média
// - mostre na tela os respectivos resultados.

// Autor(a)    : Magno
// Data atual  : 11/10/2022

Var

Inicio

Fimalgoritmo