Algoritmo "Aula 09 - Procedimento sem parâmetro"
// Disciplina   : Criação de Aplicações
// Professor   : Lucy Mari
// Data atual  : 01/11/2022

procedimento soma
var
aux: inteiro
inicio
aux <- n1 + n2
res <- aux
fimprocedimento


Var
res, n1, n2: inteiro

Inicio

escreva("Digite o 1º número: ")
leia(n1)
escreva("Digite o 2º número: ")
leia(n2)
soma
escreval
escreva("O resultado é:", res)
escreval

Fimalgoritmo