Algoritmo "Aula_06 - ENQUANTO"
// Disciplina   : Criações de aplicações
// Professor   : Frank Portela
// Data atual  : 20/10/2022
// Vale lembrar que o comando ENQUANTO necessita de um CONTADOR para dar
// sequencia a linha de código. Caso contrário, ficará infinitamente preso
// no primeiro número que encontrar.
Var

num, x, r: inteiro

Inicio

escreva("Digite um número: ")
leia(num)
enquanto x <= 10 faca
  x <- x + 1
  r <- num * x
  escreval(num," *",x," =",r)
fimenquanto
Fimalgoritmo