Algoritmo "Aula 10 - Procedimento com Parâmetro"
// Disciplina   : Criação de Aplicações
// Professor   : Lucy Mari
// Data atual  : 01/11/2022

procedimento soma(x,y:inteiro)
var
aux:inteiro
inicio
aux <- x + y
res <- aux
fimprocedimento

Var
res, n, m, a, b, w, k:inteiro

Inicio
n <- 4
m <- 9
soma(n,m)
escreval(res)
a <- 10
b <- 5
soma(a,b)
escreval(res)
w <- 2
k <- 4
soma(w,k)
escreval(res)

Fimalgoritmo