Algoritmo "Aula 12 - Função com Parâmetro"
// Disciplina   : Criação de Aplicações
// Professor   : Lucy Mari
// Data atual  : 08/11/2022

funcao Tela(texto:caractere):caractere
var
frase:caractere
inicio
frase <- texto
retorne frase
fimfuncao

funcao soma(x,y:inteiro):inteiro
var
inicio
retorne x + y
fimfunção

Var
m,n: inteiro

Inicio

escreval("Mensagem da função:")
escreval(Tela("seja bem-vindo!!!"))
n <- 10
m <- 15
escreval("O Resultado da soma é",soma(n,m))

Fimalgoritmo