Algoritmo "Raphael"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/10/2022
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Raphael Magno")
// Todo TEXTO precisa estar entre ASPAS DUPLAS.
// RUN = botão executar ou F9

Fimalgoritmo